export const TREE_NODE_TOGGLE = 'TOGGLE_TREE_NODE';
export const TREE_NODE_EXPAND = 'TREE_NODE_EXPAND';
export const TREE_NODE_COLLAPSE = 'TREE_NODE_COLLAPSE';

export const COLLAPSE_TOGGLE = 'TOGGLE_COLLAPSE';
export const COLLAPSE_OPEN = 'OPEN_COLLAPSE';
export const COLLAPSE_CLOSE = 'CLOSE_COLLAPSE';
